version: '3'

services:
    database:
        image: 'postgres:latest'
        hostname: 'postgres'
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        networks:
            - pumphouse
    backend:
        image: 'pumphouse-backend:latest'
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        env_file: .env
        depends_on:
            - database
        networks:
            - pumphouse

networks:
    pumphouse:
        driver: bridge
